# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ .Release.Name }}-ingress
#   annotations:
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/hostname: {{ .Values.ingress.host }} 
#     alb.ingress.kubernetes.io/target-type: ip
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#     - host: demo.{{ .Values.ingress.host }}  
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: {{ .Release.Name }}-service
#                 port:
#                   number: 80

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: grafana-ingress
#   annotations:
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/hostname: grafana.{{ .Values.ingress.host }} 
#     alb.ingress.kubernetes.io/target-type: ip
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#     - host: grafana.{{ .Values.ingress.host }}  # Dynamically use ingress.host for Grafana
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: grafana-service
#                 port:
#                   number: 80
