---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common
      - unzip
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Install Docker engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Create app directory
  file:
    path: /opt/app
    state: directory
    mode: '0755'

- name: Copy Docker Compose file
  template:
    src: docker-compose.yml.j2
    dest: /opt/app/docker-compose.yml
    mode: '0644'

- name: Copy nginx.conf file
  template:
    src: nginx.conf.j2
    dest: /opt/app/nginx.conf
    mode: '0644'

- name: Run Docker Compose
  command: docker-compose up -d
  args:
    chdir: /opt/app

