app:
  name: demo
namespace: argocd
image:
  repository: thejurist/demo-project
  tag: V1.0.5

replicaCount: 2

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: demo.thejurist.org.uk
  scheme: internet-facing 
  group: argocd

javaOpts: "-Xms256m -Xmx512m"

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
storage:
  size: 1Gi